apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

# Reference the Tailscale operator manifests as a remote base. Argo CD will run
# kustomize and fetch the resources from the upstream repository when syncing.
resources:
  - github.com/tailscale/tailscale//manifests/operator?ref=main
